// src/app/shared/invoice-issuer.config.ts
export interface InvoiceIssuer {
  legalName:      string;
  legalForm?:     string;              // S.r.l., S.p.A., sl.
  address:        string;
  zipcode:        string;
  city:           string;
  country:        string;
  vatNumber:      string;
  rea?:           string;
  shareCapital?:  string;
  email?:         string;
  phone?:         string;
}

export const INVOICE_ISSUER: InvoiceIssuer = {
  // TODO: овде ќе ги ставите официјалните податоци кога ќе ги добиете
  legalName: 'DBStore S.r.l.',
  legalForm: 'S.r.l.',
  address: 'Via Example 123',
  zipcode: '00100',
  city: 'Roma (RM)',
  country: 'Italy',
  vatNumber: 'IT00000000000',
  rea: 'REA RM-1234567',
  shareCapital: '€ 10.000,00 i.v.',
  email: 'info@dbstore.online',
  phone: '+39 000 000000'
};

// VAT / tax regime текст – исто ќе го замениш кога ќе биде официјален
export const INVOICE_VAT_NOTE = `Operazione non soggetta ad IVA ai sensi dell'art. XX, comma X, DPR 633/72.`;


// Опционално: disclaimer додека не е 100% правно валидиран документот
export const INVOICE_DISCLAIMER = `
  This document is generated by the DBStore platform.
  If some fiscal requirements change, the official accounting records prevail.
`;
