// src/app/shared/invoice-issuer.config.ts
export interface InvoiceIssuer {
  legalName:      string;
  legalForm?:     string;              // S.r.l., S.p.A., sl.
  address:        string;
  zipcode:        string;
  city:           string;
  country:        string;
  vatNumber:      string;
  //rea?:         string;
  email?:         string;
  //phone?:       string;
}

export const INVOICE_ISSUER: InvoiceIssuer = {
  legalName:  'Etabeta Ltd',
  legalForm:  '',
  address:    '3, Advance Business Centre, Triq Guze Flores',
  zipcode:    'SVR1950',
  city:       'RomaSanta Venera',
  country:    'Malta',
  vatNumber:  'MT30678428',
  //rea:      'REA RM-1234567',
  email:      'finance@dbstore.online',
  //phone:    '+39 000 000000'
};

// VAT / tax regime текст – исто ќе го замениш кога ќе биде официјален
export const INVOICE_VAT_NOTE = `E406: Exempt by virtue of Art 7 of the Twelfth Schedule to the Value Added Tax Act - Chapter 406`;


// Опционално: disclaimer додека не е 100% правно валидиран документот
export const INVOICE_DISCLAIMER = `This document is generated by the DBStore platform.If some fiscal requirements change, the official accounting records prevail.`;
